{
  "formatVersion": "1.1",
  "component": {
    "group": "app.judo",
    "module": "judo-sdk",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "judo-sdk-1.6.1.aar",
          "url": "judo-sdk-1.6.1.aar",
          "size": 4131143,
          "sha512": "75f18d724fdbb6e8c8550afd549930bad31d9ee4dc5d59d71ccbbaaff5f538dbae74d04a9a208e5e19d7b99f0790d5737271816f2f928fa2f2c28e32c24cad1b",
          "sha256": "b1c6f159194b4697d81a4448e18712c08b9012a6ecc50addabd0c07ccb8ad645",
          "sha1": "5b2aa6a1e56427b7fe29cbc65c12c803ad4ab240",
          "md5": "488ec6150e61dfaf691d5f45838d464d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "app.judo.libs",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "app.judo.libs",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "app.judo.libs",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "app.judo.libs",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-base",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-gif",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.6.3"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "judo-sdk-1.6.1.aar",
          "url": "judo-sdk-1.6.1.aar",
          "size": 4131143,
          "sha512": "75f18d724fdbb6e8c8550afd549930bad31d9ee4dc5d59d71ccbbaaff5f538dbae74d04a9a208e5e19d7b99f0790d5737271816f2f928fa2f2c28e32c24cad1b",
          "sha256": "b1c6f159194b4697d81a4448e18712c08b9012a6ecc50addabd0c07ccb8ad645",
          "sha1": "5b2aa6a1e56427b7fe29cbc65c12c803ad4ab240",
          "md5": "488ec6150e61dfaf691d5f45838d464d"
        }
      ]
    }
  ]
}
