{
  "formatVersion": "1.1",
  "component": {
    "group": "app.judo",
    "module": "judo-sdk",
    "version": "1.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "judo-sdk-1.13.0.aar",
          "url": "judo-sdk-1.13.0.aar",
          "size": 3978834,
          "sha512": "de617633d171105c51f4fa1e738821e13d083a32716fecf53235e8f99bd803bba3a7b2f6dbf89dbab1b620c58f23b6a2ab9bf951842598614f81683e6fc13117",
          "sha256": "d276a351b492887327337377b24a1262e66aae8ada91d471da8a6175b5c10cea",
          "sha1": "d8fb7804a23a461a04607b20c8d8a5f736080022",
          "md5": "8872d0ed45b254ffdcc7158a00eadadd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "app.judo.libs",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "app.judo.libs",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "app.judo.libs",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "app.judo.libs",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-base",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-gif",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.6.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "app.judo",
          "module": "compose",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "judo-sdk-1.13.0.aar",
          "url": "judo-sdk-1.13.0.aar",
          "size": 3978834,
          "sha512": "de617633d171105c51f4fa1e738821e13d083a32716fecf53235e8f99bd803bba3a7b2f6dbf89dbab1b620c58f23b6a2ab9bf951842598614f81683e6fc13117",
          "sha256": "d276a351b492887327337377b24a1262e66aae8ada91d471da8a6175b5c10cea",
          "sha1": "d8fb7804a23a461a04607b20c8d8a5f736080022",
          "md5": "8872d0ed45b254ffdcc7158a00eadadd"
        }
      ]
    }
  ]
}
