{
  "formatVersion": "1.1",
  "component": {
    "group": "app.judo",
    "module": "judo-sdk",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "judo-sdk-1.4.0.aar",
          "url": "judo-sdk-1.4.0.aar",
          "size": 4147773,
          "sha512": "29f3ebf8d5258e9b939f7eb8d808ab3da5702cd22b018becb60c5bf8ba54cddb5d1c6c9b877341e911ce5900511515ddaf3d3eff2525f6a791c396409d4e4d80",
          "sha256": "bab3be62755ddd84b47814e2f43599c3d8af9e553fa6cdaaad61ac3158fe0521",
          "sha1": "bca3f3645d627fb845ed0a2d44b87802b756da24",
          "md5": "1d2580ddd60ea4003deea788b8fe1ae8"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "app.judo.libs",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "app.judo.libs",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "app.judo.libs",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "app.judo.libs",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-base",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-gif",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.6.3"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "judo-sdk-1.4.0.aar",
          "url": "judo-sdk-1.4.0.aar",
          "size": 4147773,
          "sha512": "29f3ebf8d5258e9b939f7eb8d808ab3da5702cd22b018becb60c5bf8ba54cddb5d1c6c9b877341e911ce5900511515ddaf3d3eff2525f6a791c396409d4e4d80",
          "sha256": "bab3be62755ddd84b47814e2f43599c3d8af9e553fa6cdaaad61ac3158fe0521",
          "sha1": "bca3f3645d627fb845ed0a2d44b87802b756da24",
          "md5": "1d2580ddd60ea4003deea788b8fe1ae8"
        }
      ]
    }
  ]
}
