{
  "formatVersion": "1.1",
  "component": {
    "group": "app.judo",
    "module": "compose",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "compose-1.0.0.aar",
          "url": "compose-1.0.0.aar",
          "size": 3562975,
          "sha512": "3b304da6173ca5863c68c03ca291bc8b4cbbaed0cb6864fa9ec36734735e9470555cf40974af510c7644c0f5c58964153f9c3248d078778a65df59811f800f75",
          "sha256": "14c3bc88cf1e426f1a8f7fd87c0606d33045ed879e90d7979200abf06264b5e1",
          "sha1": "4b582461e86ceb674c6c8acfcea700a2d92307c5",
          "md5": "2005b155addedaa35ca172230f959fa9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "app.judo.libs",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "app.judo.libs",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "app.judo.libs",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "app.judo.libs",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.6.3"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-gif",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "compose-1.0.0.aar",
          "url": "compose-1.0.0.aar",
          "size": 3562975,
          "sha512": "3b304da6173ca5863c68c03ca291bc8b4cbbaed0cb6864fa9ec36734735e9470555cf40974af510c7644c0f5c58964153f9c3248d078778a65df59811f800f75",
          "sha256": "14c3bc88cf1e426f1a8f7fd87c0606d33045ed879e90d7979200abf06264b5e1",
          "sha1": "4b582461e86ceb674c6c8acfcea700a2d92307c5",
          "md5": "2005b155addedaa35ca172230f959fa9"
        }
      ]
    }
  ]
}
